version: "3"

services:
  db:
    image: postgres:12
    container_name: db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: djangowebsite
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    command: > 
      /bin/sh -c "
      /app/wait-for-it.sh db:5432 -- python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py createsuperuser --noinput &&
      python manage.py runserver 0.0.0.0:80"
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db