version: "3"

services:
  db:
    image: postgres:12
    container_name: db
    volumes:
      - ~/.pg/pg_data/app:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: djangowebsite
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    command: > 
      /bin/sh -c "
      /app/wait-for-it.sh db:5432 -- python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py createsuperuser --noinput &&
      python manage.py runserver 0.0.0.0:80"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: app_nginx
    image: app_nginx
    volumes:
      - www-html:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
      - etc-letsencrypt:/etc/letsencrypt
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web
    env_file:
      - .env
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email aldiarm27@gmail.com --agree-tos --no-eff-email


volumes:
  static_volume:
  media_volume:
  www-html:
  etc-letsencrypt: