# Generated by Django 4.2.7 on 2023-11-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_of_machine',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
