# Generated by Django 4.2.7 on 2023-11-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_of_machine_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_of_machine',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
