# Generated by Django 4.2.7 on 2023-11-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_of_machine_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='')),
                ('in_stock', models.CharField(choices=[('В наличии', 'В наличии'), ('Под заказ', 'Под заказ')], max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
