# Generated by Django 4.2.7 on 2023-11-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_machines'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='machines',
            name='info_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='machines',
            name='name_2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='machines',
            name='video_link',
            field=models.TextField(default=''),
        ),
    ]
