# Generated by Django 4.2.7 on 2023-12-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_machines_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
