# Generated by Django 4.2.7 on 2023-12-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_machines_photo_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='info_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
