# Generated by Django 4.2.7 on 2023-12-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_machines_info_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='video_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
